services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - paytjek-network

  backend:
    build: ./backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env                           # <-- henter DATABASE_URL, MISTRAL_API_KEY, CORS_ORIGINS mv.
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      # Bemærk: DATABASE_URL hentes via env_file, så den skal ikke listes her
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - paytjek-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./Frontend/src:/app/src:cached
      - ./Frontend/public:/app/public:cached
      - ./Frontend/index.html:/app/index.html:cached
      - ./Frontend/vite.config.ts:/app/vite.config.ts:cached
      - ./Frontend/tsconfig.json:/app/tsconfig.json:cached
      - ./Frontend/tailwind.config.ts:/app/tailwind.config.ts:cached
      - ./Frontend/postcss.config.js:/app/postcss.config.js:cached
      - ./Frontend/package.json:/app/package.json:cached
    restart: unless-stopped
    networks:
      - paytjek-network

networks:
  paytjek-network:
    driver: bridge

volumes:
  db_data:
