version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - paytjek-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_HMR_PORT=8080
    volumes:
      - ./Frontend/src:/app/src
      - ./Frontend/public:/app/public
      - ./Frontend/index.html:/app/index.html
      - ./Frontend/vite.config.ts:/app/vite.config.ts
      - ./Frontend/tsconfig.json:/app/tsconfig.json
      - ./Frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ./Frontend/postcss.config.js:/app/postcss.config.js
      - ./Frontend/package.json:/app/package.json
    restart: unless-stopped
    networks:
      - paytjek-network

volumes:
  postgres_data:

networks:
  paytjek-network:
    driver: bridge
