version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - CORS_ORIGINS=http://localhost:8080,http://localhost:8081,http://frontend:80
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.simple
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Frontend/dist:/usr/share/nginx/html
    restart: unless-stopped 