"""Add ics_url and workplace to User model

Revision ID: c65f0607867c
Revises: 01310fc64547
Create Date: 2025-04-22 11:10:10.760267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65f0607867c'
down_revision: Union[str, None] = '01310fc64547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ics_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('workplace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'workplace')
    op.drop_column('users', 'ics_url')
    # ### end Alembic commands ###
