"""create users, payslips & shifts

Revision ID: c87002d34949
Revises: 
Create Date: 2025-04-21 11:45:15.602647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87002d34949'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('payslips',
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dato', sa.Date(), nullable=False),
    sa.Column('arbejdstimer', sa.Float(), nullable=True),
    sa.Column('loen_brutto', sa.Float(), nullable=True),
    sa.Column('fradrag_total', sa.Float(), nullable=True),
    sa.Column('loen_netto', sa.Float(), nullable=True),
    sa.Column('fil_sti', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payslip_id')
    )
    op.create_index(op.f('ix_payslips_payslip_id'), 'payslips', ['payslip_id'], unique=False)
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dato', sa.Date(), nullable=False),
    sa.Column('start_tid', sa.DateTime(), nullable=True),
    sa.Column('slut_tid', sa.DateTime(), nullable=True),
    sa.Column('timer', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shifts_shift_id'), 'shifts', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_shift_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_payslips_payslip_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
